name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Instalar PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: '8.2'
          tools: composer

      - name: Instalar dependencias
        run: composer install

      - name: Ejecutar tests
        run: vendor/bin/phpunit --testdox tests

  construir:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    #- name: Obtener tag
    #  uses: olegtarasov/get-tag@v2.1.4
    #  id: tagName
    #  with:
    #    tagname: ${{ steps.tagName.outputs.tag }}

    - name: Obtener tag
      id: tagName
      uses: olegtarasov/get-tag@v2.1.4

    - name: Verificar tag obtenido
      run: echo "Tag obtenido: ${{ steps.tagName.outputs.tag }}"

    
    - name: Login en Docker
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - uses: actions/checkout@v4

    - name: Configurar QEMU
      uses: docker/setup-qemu-action@v3.3.0

    - name: Configurar Buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: Construir y subir imagen Docker
      uses: docker/build-push-action@v6.13.0
      with:
        push: true
        tags: ${{ secrets.DOCKER_USER }}/calculadora:${{ steps.tagName.outputs.tag }}
        platforms: linux/amd64,linux/arm64
