name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Instalar PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: '8.2'

      - name: Instalar dependencias
        run: composer install --no-dev

      - name: Ejecutar tests
        run: vendor/bin/phpunit tests
          
        

  construir:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login en Docker
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.3.0

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.13.0
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USER }}/calculadora:latest
        platforms: linux/amd64,linux/arm64

     
     
    #- name: Montar imagen
    #  run: docker build -t ${{secrets.DOCKER_USER}}/calculadora:latest .

    #- name: Subir imagen a dockerhub
    #  run: |
    #    echo "Subiendo imagen..."
    #    docker push ${{secrets.DOCKER_USER}}/calculadora:latest
