name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login en Docker
      run: |
        echo "Logueandose...."
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}}
        
    - name: Montar imagen
      run: docker build -t ${{secrets.DOCKER_USER}}/calculadora:latest .

    - name: Subir imagen a dockerhub
      run: |
        echo "Subiendo imagen..."
        docker push ${{secrets.DOCKER_USER}}/calculadora:latest
